### ISSUE TITLE
can't communicate ?

### ISSUE THREAD

**Issue by irom77** [colebrumley/docker-etcd#7]
I have it running but can't communicate i.e. curl -L http://127.0.0.1:2379/version.

**Comment by romankh3** [comment]
the same question! I ran this image, but can not communicate with it.

**Comment by colebrumley** [comment]
Hmm, what settings are you using? I gotta give the classic response: _works on my machine_! After pulling `:latest` I am getting:

```
[ 0 ] cole@systemc:~$ docker run -d -p 2379:2379 elcolio/etcd
6c6918053f1d934ea912a0342aded12d673d72568e5c3f4f0f97ca8886691d30
[ 0 ] cole@systemc:~$ curl http://localhost:2379/version
etcd 2.0.10
```

I will freely admit that I am not using etcd much these days, so I could be missing something obvious.

**Comment by irom77** [comment]
I think I used wrong port ..sorry
